from livekit.agents import function_tool, RunContext

from shared.config.logger import get_logger
from shared.config.constants import TicketPriority

from shared.infra.crm.mock import get_mockcrmclient
from shared.infra.redis.customer_cache import get_cached_customer, cache_customer


_LOGGER = "worker.domain.tools.crm"
logger = get_logger(_LOGGER)


def customer_profile_formatter(customer_profile: dict) -> str:
    """
    Formats a customer profile dictionary into a natural language string.
    
    Args:
        customer_profile (dict): The customer data retrieved from the cache or CRM.
        
    Returns:
        str: A human-readable summary of the customer's account status.
    """
    return (
        f"Customer {customer_profile['name']} is on the "
        f"{customer_profile['current_plan']} plan since "
        f"{customer_profile['plan_since']} with "
        f"{customer_profile['usage_percent']}% usage and "
        f"{customer_profile['open_tickets']} open tickets."
    )
    

@function_tool
async def get_customer_profile(
        ctx: RunContext, 
        identifier: str,
    ) -> str:
    """
    Retrieves a formatted customer profile using their unique identifier.
    
    Checks the Redis cache first. If the data is not found, it fetches 
    it directly from the CRM and caches the result for future queries.

    Args:
        ctx (RunContext): The LiveKit agent execution context.
        identifier (str): The unique identifier for the customer (e.g., phone number or Clerk ID).

    Returns:
        str: A natural language summary of the customer's profile, or a 
             message indicating they are a new caller.
    """
    try:
        customer_profile = await get_cached_customer(identifier)

        if customer_profile:
            logger.debug(f"Retrieved customer profile from cache — identifier={identifier}")
            return customer_profile_formatter(customer_profile)

        crm_client = get_mockcrmclient()
        customer_profile = await crm_client.get_customer(identifier)

        if not customer_profile:
            logger.debug(f"No existing profile found in CRM — identifier={identifier}")
            return "This is a new caller with no existing account on file."

        await cache_customer(identifier, customer_profile)

        logger.debug(f"Retrieved customer profile from CRM and cached — identifier={identifier}")
        # DRY applied: Replaced the duplicate f-string block with your formatter helper
        return customer_profile_formatter(customer_profile)
        
    except Exception as e:
        logger.error(f"Failed to retrieve customer profile — identifier={identifier} error={e}")
        raise 


@function_tool
async def create_ticket(
        ctx: RunContext,
        customer_id: str,
        description: str,
        priority: str = "normal"
    ) -> str:
    """
    Creates a new customer support ticket in the CRM system.

    Args:
        ctx (RunContext): The LiveKit agent execution context.
        customer_id (str): The unique ID of the customer experiencing the issue.
        description (str): A detailed description of the customer's issue or request.
        priority (str, optional): The urgency level ("low", "normal", "high"). Defaults to "normal".

    Returns:
        str: The unique Ticket ID generated by the CRM.
    """
    try:
        
        priority_map = {
            "low": TicketPriority.LOW,
            "normal": TicketPriority.NORMAL,
            "high": TicketPriority.HIGH
        }   
        ticket_priority = priority_map.get(priority.lower(), TicketPriority.NORMAL)

        crm_client = get_mockcrmclient()
        ticket = await crm_client.create_ticket(customer_id, description, ticket_priority)
        
        logger.debug(f"Created support ticket — customer_id={customer_id} ticket_id={ticket} priority={ticket_priority.value}")
        return ticket
    except Exception as e:
        logger.error(f"Failed to create support ticket — customer_id={customer_id} error={e}")
        raise